# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/t6/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/t6/proprietary/blobs/gsm/bin/efsks:system/vendor/blobs/gsm/bin/efsks \
    vendor/htc/t6/proprietary/blobs/gsm/bin/netmgrd:system/vendor/blobs/gsm/bin/netmgrd \
    vendor/htc/t6/proprietary/blobs/gsm/bin/qcks:system/vendor/blobs/gsm/bin/qcks \
    vendor/htc/t6/proprietary/blobs/gsm/bin/qmuxd:system/vendor/blobs/gsm/bin/qmuxd \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libdiag.so:system/vendor/blobs/gsm/lib/libdiag.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libdsi_netctrl.so:system/vendor/blobs/gsm/lib/libdsi_netctrl.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libdsutils.so:system/vendor/blobs/gsm/lib/libdsutils.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libidl.so:system/vendor/blobs/gsm/lib/libidl.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libnetmgr.so:system/vendor/blobs/gsm/lib/libnetmgr.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqcci_legacy.so:system/vendor/blobs/gsm/lib/libqcci_legacy.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqdi.so:system/vendor/blobs/gsm/lib/libqdi.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqdp.so:system/vendor/blobs/gsm/lib/libqdp.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqmi.so:system/vendor/blobs/gsm/lib/libqmi.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqmi_cci.so:system/vendor/blobs/gsm/lib/libqmi_cci.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqmi_client_qmux.so:system/vendor/blobs/gsm/lib/libqmi_client_qmux.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqmi_common_so.so:system/vendor/blobs/gsm/lib/libqmi_common_so.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqmi_csi.so:system/vendor/blobs/gsm/lib/libqmi_csi.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqmi_encdec.so:system/vendor/blobs/gsm/lib/libqmi_encdec.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libqmiservices.so:system/vendor/blobs/gsm/lib/libqmiservices.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libril-qc-qmi-1.so:system/vendor/blobs/gsm/lib/libril-qc-qmi-1.so \
    vendor/htc/t6/proprietary/blobs/gsm/lib/libril-qcril-hook-oem.so:system/vendor/blobs/gsm/lib/libril-qcril-hook-oem.so \
    vendor/htc/t6/proprietary/blobs/spr/bin/efsks:system/vendor/blobs/spr/bin/efsks \
    vendor/htc/t6/proprietary/blobs/spr/bin/netmgrd:system/vendor/blobs/spr/bin/netmgrd \
    vendor/htc/t6/proprietary/blobs/spr/bin/qcks:system/vendor/blobs/spr/bin/qcks \
    vendor/htc/t6/proprietary/blobs/spr/bin/qmuxd:system/vendor/blobs/spr/bin/qmuxd \
    vendor/htc/t6/proprietary/blobs/spr/lib/libdiag.so:system/vendor/blobs/spr/lib/libdiag.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libdsi_netctrl.so:system/vendor/blobs/spr/lib/libdsi_netctrl.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libdsutils.so:system/vendor/blobs/spr/lib/libdsutils.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libidl.so:system/vendor/blobs/spr/lib/libidl.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libnetmgr.so:system/vendor/blobs/spr/lib/libnetmgr.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqcci_legacy.so:system/vendor/blobs/spr/lib/libqcci_legacy.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqdi.so:system/vendor/blobs/spr/lib/libqdi.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqdp.so:system/vendor/blobs/spr/lib/libqdp.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqmi.so:system/vendor/blobs/spr/lib/libqmi.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqmi_cci.so:system/vendor/blobs/spr/lib/libqmi_cci.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqmi_client_qmux.so:system/vendor/blobs/spr/lib/libqmi_client_qmux.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqmi_common_so.so:system/vendor/blobs/spr/lib/libqmi_common_so.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqmi_csi.so:system/vendor/blobs/spr/lib/libqmi_csi.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqmi_encdec.so:system/vendor/blobs/spr/lib/libqmi_encdec.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libqmiservices.so:system/vendor/blobs/spr/lib/libqmiservices.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libril-qc-qmi-1.so:system/vendor/blobs/spr/lib/libril-qc-qmi-1.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libril-qcril-hook-oem.so:system/vendor/blobs/spr/lib/libril-qcril-hook-oem.so \
    vendor/htc/t6/proprietary/blobs/spr/lib/libtime_genoff.so:system/vendor/blobs/spr/lib/libtime_genoff.so \
    vendor/htc/t6/proprietary/blobs/vzw/bin/efsks:system/vendor/blobs/vzw/bin/efsks \
    vendor/htc/t6/proprietary/blobs/vzw/bin/netmgrd:system/vendor/blobs/vzw/bin/netmgrd \
    vendor/htc/t6/proprietary/blobs/vzw/bin/qcks:system/vendor/blobs/vzw/bin/qcks \
    vendor/htc/t6/proprietary/blobs/vzw/bin/qmuxd:system/vendor/blobs/vzw/bin/qmuxd \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libdiag.so:system/vendor/blobs/vzw/lib/libdiag.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libdsi_netctrl.so:system/vendor/blobs/vzw/lib/libdsi_netctrl.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libdsutils.so:system/vendor/blobs/vzw/lib/libdsutils.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libidl.so:system/vendor/blobs/vzw/lib/libidl.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libnetmgr.so:system/vendor/blobs/vzw/lib/libnetmgr.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqcci_legacy.so:system/vendor/blobs/vzw/lib/libqcci_legacy.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqdi.so:system/vendor/blobs/vzw/lib/libqdi.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqdp.so:system/vendor/blobs/vzw/lib/libqdp.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqmi.so:system/vendor/blobs/vzw/lib/libqmi.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqmi_cci.so:system/vendor/blobs/vzw/lib/libqmi_cci.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqmi_client_qmux.so:system/vendor/blobs/vzw/lib/libqmi_client_qmux.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqmi_common_so.so:system/vendor/blobs/vzw/lib/libqmi_common_so.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqmi_csi.so:system/vendor/blobs/vzw/lib/libqmi_csi.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqmi_encdec.so:system/vendor/blobs/vzw/lib/libqmi_encdec.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libqmiservices.so:system/vendor/blobs/vzw/lib/libqmiservices.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libril-qc-qmi-1.so:system/vendor/blobs/vzw/lib/libril-qc-qmi-1.so \
    vendor/htc/t6/proprietary/blobs/vzw/lib/libril-qcril-hook-oem.so:system/vendor/blobs/vzw/lib/libril-qcril-hook-oem.so \
    vendor/htc/t6/proprietary/blobs/tl/bin/efsks:system/vendor/blobs/tl/bin/efsks \
    vendor/htc/t6/proprietary/blobs/tl/bin/netmgrd:system/vendor/blobs/tl/bin/netmgrd \
    vendor/htc/t6/proprietary/blobs/tl/bin/qcks:system/vendor/blobs/tl/bin/qcks \
    vendor/htc/t6/proprietary/blobs/tl/bin/qmuxd:system/vendor/blobs/tl/bin/qmuxd \
    vendor/htc/t6/proprietary/blobs/tl/lib/libdiag.so:system/vendor/blobs/tl/lib/libdiag.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libdsi_netctrl.so:system/vendor/blobs/tl/lib/libdsi_netctrl.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libdsutils.so:system/vendor/blobs/tl/lib/libdsutils.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libidl.so:system/vendor/blobs/tl/lib/libidl.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libnetmgr.so:system/vendor/blobs/tl/lib/libnetmgr.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqcci_legacy.so:system/vendor/blobs/tl/lib/libqcci_legacy.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqdi.so:system/vendor/blobs/tl/lib/libqdi.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqdp.so:system/vendor/blobs/tl/lib/libqdp.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqmi.so:system/vendor/blobs/tl/lib/libqmi.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqmi_cci.so:system/vendor/blobs/tl/lib/libqmi_cci.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqmi_client_qmux.so:system/vendor/blobs/tl/lib/libqmi_client_qmux.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqmi_common_so.so:system/vendor/blobs/tl/lib/libqmi_common_so.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqmi_csi.so:system/vendor/blobs/tl/lib/libqmi_csi.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqmi_encdec.so:system/vendor/blobs/tl/lib/libqmi_encdec.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libqmiservices.so:system/vendor/blobs/tl/lib/libqmiservices.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libril-qc-qmi-1.so:system/vendor/blobs/tl/lib/libril-qc-qmi-1.so \
    vendor/htc/t6/proprietary/blobs/tl/lib/libril-qcril-hook-oem.so:system/vendor/blobs/tl/lib/libril-qcril-hook-oem.so
