# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/e8-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter e8 e8d,$(TARGET_DEVICE)),)

ifeq ($(strip $(BOARD_NFC_CHIPSET)),pn547)
include $(CLEAR_VARS)
LOCAL_MODULE := nfc_nci.msm8974
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/vendor/lib/hw/nfc_nci.msm8974.so
LOCAL_CHECK_ELF_FILES := false
LOCAL_MULTILIB := 32
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

endif

endif
