# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/t6/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/t6d/proprietary/bin/efsks:system/bin/efsks \
    vendor/htc/t6d/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/htc/t6d/proprietary/bin/qcks:system/bin/qcks \
    vendor/htc/t6d/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/htc/t6d/proprietary/bin/rild_qsc:system/bin/rild_qsc \
    vendor/htc/t6d/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/htc/t6d/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/htc/t6d/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/htc/t6d/proprietary/lib/libhtc_rilhook.so:system/lib/libhtc_rilhook.so \
    vendor/htc/t6d/proprietary/lib/libhtc_rilhook_qsc.so:system/lib/libhtc_rilhook_qsc.so \
    vendor/htc/t6d/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/htc/t6d/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/htc/t6d/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/htc/t6d/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/htc/t6d/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/htc/t6d/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/htc/t6d/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/htc/t6d/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/htc/t6d/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/htc/t6d/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/htc/t6d/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/htc/t6d/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/htc/t6d/proprietary/lib/libril_qsc.so:system/lib/libril_qsc.so \
    vendor/htc/t6d/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/htc/t6d/proprietary/lib/libril-qc-qmi-qsc.so:system/lib/libril-qc-qmi-qsc.so \
    vendor/htc/t6d/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so
